spring.application.name=demo2
server.port=8081
spring.docker.compose.enabled=false

# mysqlデータベース接続設定
spring.datasource.url=jdbc:mysql://localhost:3306/practice_db?serverTimezone=Asia/Tokyo&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# jpa設定　Entityクラスに合わせて自動でテーブル作成
spring.jpa.hibernate.ddl-auto=update

# ログの設定
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true